#!/bin/bash

set -e

cd $(dirname "${BASH_SOURCE[0]}")

echo "mcc,country" > mccs.tmp
curl -s -L "http://mcc-mnc.com/" \
| grep -Eo  "\s<tr><td>[0-9]{3}</td><td>[0-9]+</td><td>[a-z]+</td><td>[^<]+" \
| awk -F'<td>|</td>' '{print $2",\""$8"\""}' | sort -V | uniq \
| sed -r 's/\s+"/"/g' \
| sed 's/Israel/Israel \/ Palestine/g' \
| grep -Ev '"Guam"|"Guadeloupe"|"Martinique"|"Bonaire, Sint Eustatius and Saba"|"Curacao"|"Virgin Islands"|"Palestine"' \
| sort -t, -k2 \
>> mccs.tmp

if [[ $(cat mccs.tmp | wc -l) > 100 ]]; then
  mv -f mccs.tmp mccs.csv
else 
  rm mccs.tmp
fi
