name: Build and publish lacells website
on:
  push:
    branches: [ master ]
  schedule:
    - cron: 0 2 * * 1,4

jobs:
  publish:
    name: Build and publish
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install --no-install-recommends -y file sqlite3 git wget
      - name: Download and split
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: ./lacells-creator -d -i -m -e -q
      - name: Prepare website
        run: |
          mkdir -p lacells.git
          cd lacells.git
          git init -q
          git config user.email lacells
          git config user.name lacells
          git remote add origin git@github.com:wvengen/lacells.git
          git branch --set-upstream-to origin
      - name: Publish website
        env:
          LACELLS_GIT_SSH_KEY: ${{ secrets.LACELLS_GIT_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh && chmod 0700 ~/.ssh
          echo "$LACELLS_GIT_SSH_KEY" >~/.ssh/id_rsa
          ./misc/upload-git
